### PR TITLE
ICON XPP and NextGEMS

### PR DESCRIPTION
**Pull request by SF-N**

### CODE REVIEW

**Comment by juntyr** [comment]
Is it possible to also plot the NextGEMS data using earthkit?

In the ICON XPP data, the plots have very weird latitude and longitude scales. Just to check (no need to update the notebook, just check locally), does simply plotting the raw data using matplotlib imshow show the same data or is earthkit accidentally only plotting a small subset?

**Comment by juntyr** [comment]
Some quick feedback:
- please also update the READMEs
- https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.
- nextGEMS:
  - first sentence: "This notebook is a comprehensive guide to accessing a Zarr dataset"
  - I think the paragraph on experimental details mixes information as it contradicts between small subset of data and a 1000 year long run
  - you will also need to import aiohttp and dask
  - pyicon is a new package the online lab doesn't support yet ... I'll see what I can do :)
    - this also requires support for healpy, astropy, and pyerfa ... let's see ...
- ICON:
  - you misspelled NetCDF as NetDCF (I think in some other notebooks as well, probably best to do a search and replace)
  - you can pass datetimes as strings directly (no need to pass them through np.datetime64)
  - I don't think that there's a need for the [::10] downsampling for this notebook
  - if we import cftime alongside the other imports, we can at least load data in earlier years (since xarray will then use a special cftimeindex) (though we still cannot plot it because of earthkit)

**Comment by SF-N** [comment]
Closing this as it was moved to PR #28.

**Comment by SF-N** [comment]
> Is it possible to also plot the NextGEMS data using earthkit?

I am not sure but probably yes, I will check with the earthkit developers. 

> In the ICON XPP data, the plots have very weird latitude and longitude scales. Just to check (no need to update the notebook, just check locally), does simply plotting the raw data using matplotlib imshow show the same data or is earthkit accidentally only plotting a small subset?

Thanks for pointing this out, the values were in radians instead of degrees. Rescaling them resolves this and also the problem of not showing the coastlines.

**Pull request closed without merging**
