### PR TITLE
ICON XPP and NextGEMS dataset

### PR DESCRIPTION
**Pull request by SF-N**
This replaces PR #26.
Adding 2 ICON datasets and improving other dataset notebooks.

TODOs:
- [x]  Plotting of HEALPix data with earthkit-plots in 03-NextGEMS.ipynb (Issue [37](https://github.com/ecmwf/earthkit-plots/issues/37))
- [ ] Plotting data before 1678 and after 2262 (Issue [35](https://github.com/ecmwf/earthkit-plots/issues/35))
- [x] Update READMEs
- [x] CORS warnings
- [x] add ICON-XPP licence information

### CODE REVIEW

**Comment by SF-N** [comment]
Regarding your comment in PR #26:
> https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.

I am not sure which warning you are referring to, but we tried to configure the S3 bucket.
Please let me know if the warnings still appear.

**Comment by juntyr** [comment]
> Regarding your comment in PR #26:
> 
> > https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.
> 
> I am not sure which warning you are referring to, but we tried to configure the S3 bucket. Please let me know if the warnings still appear.

The warnings are on the main branch of the lab (if you use lab.climet.eu/main). They're not gone yet and it seems the S3 bucket still does not set the `Access-Control-Allow-Origin: *` header.

**Comment by juntyr** [comment]
I've made some progress on adding `healpy` and `pyicon` but compiling `healpy` still fails (https://github.com/pyodide/pyodide/issues/5250).

I'm tracking progress here: https://github.com/climet-eu/pyodide/tree/healpy

**Comment by SF-N** [comment]
> > Regarding your comment in PR #26:
> > > https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.
> > 
> > 
> > I am not sure which warning you are referring to, but we tried to configure the S3 bucket. Please let me know if the warnings still appear.
> 
> The warnings are on the main branch of the lab (if you use lab.climet.eu/main). They're not gone yet and it seems the S3 bucket still does not set the `Access-Control-Allow-Origin: *` header.

After talking to the ECMWF user support, it seems like there is nothing that can be done on the S3 bucket side. 
When debugging with curl, the correct headers seem to be there:
```
< access-control-allow-origin: *
< access-control-allow-methods: GET
```
The warning also only pops up during the first execution.
So I guess, ignoring this warning is probably the best solution currently.

**Comment by juntyr** [comment]
> > > Regarding your comment in PR #26:
> > > > https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.
> > > 
> > > 
> > > I am not sure which warning you are referring to, but we tried to configure the S3 bucket. Please let me know if the warnings still appear.
> > 
> > 
> > The warnings are on the main branch of the lab (if you use lab.climet.eu/main). They're not gone yet and it seems the S3 bucket still does not set the `Access-Control-Allow-Origin: *` header.
> 
> After talking to the ECMWF user support, it seems like there is nothing that can be done on the S3 bucket side. When debugging with curl, the correct headers seem to be there:
> 
> ```
> < access-control-allow-origin: *
> < access-control-allow-methods: GET
> ```
> 
> The warning also only pops up during the first execution. So I guess, ignoring this warning is probably the best solution currently.

Huh, when I run

```
curl https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/ICON-XPP/slo1802_atm_2d_ml_20200101T000000Z.nc.ref -D - -o /dev/null
```

I get the following

```
content-length: 473589
accept-ranges: bytes
last-modified: Fri, 06 Dec 2024 12:35:33 GMT
x-rgw-object-type: Normal
etag: "35c2574bd69afda9fb9daba53b2c8db2"
x-amz-meta-s3cmd-attrs: atime:1733487713/ctime:1733487713/gid:20/gname:staff/md5:35c2574bd69afda9fb9daba53b2c8db2/mode:33188/mtime:1733487713/uid:501/uname:ecm5945
x-amz-storage-class: STANDARD
x-amz-request-id: tx000001d12bb387d38674d-00675735fe-149ac72b-default
content-type: binary/octet-stream
date: Mon, 09 Dec 2024 18:25:02 GMT
```

where the CORS headers are missing.

**Comment by SF-N** [comment]
> > > > Regarding your comment in PR #26:
> > > > > https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.
> > > > 
> > > > 
> > > > I am not sure which warning you are referring to, but we tried to configure the S3 bucket. Please let me know if the warnings still appear.
> > > 
> > > 
> > > The warnings are on the main branch of the lab (if you use lab.climet.eu/main). They're not gone yet and it seems the S3 bucket still does not set the `Access-Control-Allow-Origin: *` header.
> > 
> > 
> > After talking to the ECMWF user support, it seems like there is nothing that can be done on the S3 bucket side. When debugging with curl, the correct headers seem to be there:
> > ```
> > < access-control-allow-origin: *
> > < access-control-allow-methods: GET
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The warning also only pops up during the first execution. So I guess, ignoring this warning is probably the best solution currently.
> 
> Huh, when I run
> 
> ```
> curl https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/ICON-XPP/slo1802_atm_2d_ml_20200101T000000Z.nc.ref -D - -o /dev/null
> ```
> 
> I get the following
> 
> ```
> content-length: 473589
> accept-ranges: bytes
> last-modified: Fri, 06 Dec 2024 12:35:33 GMT
> x-rgw-object-type: Normal
> etag: "35c2574bd69afda9fb9daba53b2c8db2"
> x-amz-meta-s3cmd-attrs: atime:1733487713/ctime:1733487713/gid:20/gname:staff/md5:35c2574bd69afda9fb9daba53b2c8db2/mode:33188/mtime:1733487713/uid:501/uname:ecm5945
> x-amz-storage-class: STANDARD
> x-amz-request-id: tx000001d12bb387d38674d-00675735fe-149ac72b-default
> content-type: binary/octet-stream
> date: Mon, 09 Dec 2024 18:25:02 GMT
> ```
> 
> where the CORS headers are missing.

The following command shows the headers:

```
curl --verbose -H 'Origin: http://example.com' "https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/OpenIFS/HighResMIP_6h_reduced_pl_q.nc.ref" >/dev/null
```
Does that help?

**Comment by juntyr** [comment]
Dear Sara,

Now I managed to get the headers as well – thanks for your help!

Would it be possible to add HEAD to the access-control-allow-methods as well?

Best regards,
Juniper [they/them]

From: SF-N ***@***.***>
Date: Tuesday, 10. December 2024 at 12.05
To: climet-eu/compression-lab-notebooks ***@***.***>
Cc: Tyree, Juniper ***@***.***>, Comment ***@***.***>
Subject: Re: [climet-eu/compression-lab-notebooks] ICON XPP and NextGEMS dataset (PR #28)

Regarding your comment in PR #26<https://github.com/climet-eu/compression-lab-notebooks/pull/26>:

https://object-store.os-api.cci1.ecmwf.int/ doesn't support CORS (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). While the CORS proxy of the online lab makes things work in any case, it now displays a warning. Perhaps you can poke someone to reconfigure the S3 bucket? If need be I can add some special cases to the ignore code so that URLs we already use won't spam users.

I am not sure which warning you are referring to, but we tried to configure the S3 bucket. Please let me know if the warnings still appear.

The warnings are on the main branch of the lab (if you use lab.climet.eu/main). They're not gone yet and it seems the S3 bucket still does not set the Access-Control-Allow-Origin: * header.

After talking to the ECMWF user support, it seems like there is nothing that can be done on the S3 bucket side. When debugging with curl, the correct headers seem to be there:

< access-control-allow-origin: *

< access-control-allow-methods: GET

The warning also only pops up during the first execution. So I guess, ignoring this warning is probably the best solution currently.

Huh, when I run

curl https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/ICON-XPP/slo1802_atm_2d_ml_20200101T000000Z.nc.ref -D - -o /dev/null

I get the following

content-length: 473589

accept-ranges: bytes

last-modified: Fri, 06 Dec 2024 12:35:33 GMT

x-rgw-object-type: Normal

etag: "35c2574bd69afda9fb9daba53b2c8db2"

x-amz-meta-s3cmd-attrs: atime:1733487713/ctime:1733487713/gid:20/gname:staff/md5:35c2574bd69afda9fb9daba53b2c8db2/mode:33188/mtime:1733487713/uid:501/uname:ecm5945

x-amz-storage-class: STANDARD

x-amz-request-id: tx000001d12bb387d38674d-00675735fe-149ac72b-default

content-type: binary/octet-stream

date: Mon, 09 Dec 2024 18:25:02 GMT

where the CORS headers are missing.

The following command shows the headers:

curl --verbose -H 'Origin: http://example.com' "https://object-store.os-api.cci1.ecmwf.int/esiwacebucket/OpenIFS/HighResMIP_6h_reduced_pl_q.nc.ref" >/dev/null

Does that help?

**Comment by SF-N** [comment]
> Would it be possible to add HEAD to the access-control-allow-methods as well? 

Yes, this solved it. Now the warnings should not appear anymore.

**Comment by juntyr** [comment]
> > Would it be possible to add HEAD to the access-control-allow-methods as well?
> 
> Yes, this solved it. Now the warnings should not appear anymore.

Yes, it's fixed now - thanks!

**Comment by juntyr** [comment]
@SF-N `healpy` and `pyicon` now seem to work in the online lab (lab.climet.eu/main).

I saw some `earthkit.plots` examples using healpix data - so perhaps it could work for us as well?

https://earthkit-plots.readthedocs.io/en/latest/examples/gallery/grid-types/healpix-pixels.html

**Comment by SF-N** [comment]
> @SF-N `healpy` and `pyicon` now seem to work in the online lab (lab.climet.eu/main).


Great, thanks a lot!

> I saw some `earthkit.plots` examples using healpix data - so perhaps it could work for us as well?
> 
> https://earthkit-plots.readthedocs.io/en/latest/examples/gallery/grid-types/healpix-pixels.html



James said that the issue is that earthkit-plots doesn't really support HEALPix from xarray at the moment - it largely depends on eccodes to understand HEALPix, and that only works well from GRIB. He wanted to create a new issue to support HEALPix from xarray.

**Comment by juntyr** [comment]
Do you think we can get these two notebooks ready by the end of this week?

**Comment by SF-N** [comment]
> Do you think we can get these two notebooks ready by the end of this week?

From my perspective, now that pyicon works, yes. 
I am just not sure if plotting data before 1678 and after 2262 will be possible without errors by then.
The rest are just minor things.

**Comment by SF-N** [comment]
I updated the notebooks and added the licence information (still missing for ICON-XPP).
It seems like it will take some more time until [https://github.com/ecmwf/earthkit-plots/issues/35](https://github.com/ecmwf/earthkit-plots/issues/35), i.e. [https://github.com/ecmwf/earthkit-plots/issues/38](https://github.com/ecmwf/earthkit-plots/issues/38) and [https://github.com/ecmwf/earthkit-plots/issues/37](https://github.com/ecmwf/earthkit-plots/issues/37), i.e. [https://github.com/ecmwf/earthkit-plots/issues/39](https://github.com/ecmwf/earthkit-plots/issues/39) will be solved. 
We can wait a couple of more days, but then I suggest to release with the current workarounds.

**Comment by juntyr** [comment]
I'll merge now rather than wait for a few more days. It's easier to fix a few lines in two notebooks on Monday than it is to do all of the notebook updates and merging then.

**Review by juntyr — APPROVED** [review]
LGTM

**Pull request merged**
