### PR TITLE
Resturcture and add OpenIFS notebook

### PR DESCRIPTION
**Pull request by SF-N**
- Fix order of tables in hplp notebook and minor fixes
- New notebook for OpenIFS dataset
- Restructuring of notebooks

### CODE REVIEW

**Comment by juntyr** [comment]
In the text above cell [8], is that a pressure level 1hPa or a model level 1?

**Review by juntyr — APPROVED** [review]
Thanks for the restructuring and the new notebook, both look good to me!

I left one question above, once we've cleared that I'll merge the PR.

I also committed some minor tweaks

**Comment by SF-N** [comment]
> In the text above cell [8], is that a pressure level 1hPa or a model level 1?

It should be pressure level 1hPa. I fixed it, thanks for pointing this out!

I also renamed the helper functions.

**Comment by SF-N** [comment]
I think before (or after) merging this, we need to brainstorm about the structure of the directories, also having future showcases in mind. 
I can imagine that we would also want to show several compression methods applied to the data in the S3 bucket.
I am bringing this up because some files will be linked in D3.3 so they shouldn't move after submission (or should we better not link them if we are unsure about the structure?).

**Comment by juntyr** [comment]
> I think before (or after) merging this, we need to brainstorm about the structure of the directories, also having future showcases in mind.
> I can imagine that we would also want to show several compression methods applied to the data in the S3 bucket.
> I am bringing this up because some files will be linked in D3.3 so they shouldn't move after submission (or should we better not link them if we are unsure about the structure?).

Thinking about structure is important, but we’re also using git so files moving is not an issue.

My plan is to release v0.2 of the notebooks (and hopefully the lab) in mid to late December. We can then provide GitHub links to this version (and also publish v0.2 of the notebooks on Zenodo), and give versioned links for the online lab as well. compression.lab.climet.eu right now points towards v0.1 of the notebooks and v0.1 of the lab, and we’ll update that then without any of the fully resolved links to previous versions breaking. I added this versioning system precisely so we can change things and correct mistakes without any links breaking.

What might be useful to add still are some URLs just for the online compression lab, so you could e.g. use compression.lab.climet.eu/v0.1/LICENSE.txt to open specifically this file in the specific version of the lab and notebooks (my plan is to always associate the notebooks with one lab version, though these version numbers don’t need to match).

**Comment by SF-N** [comment]
> Thinking about structure is important, but we’re also using git so files moving is not an issue.
> 
> My plan is to release v0.2 of the notebooks (and hopefully the lab) in mid to late December. We can then provide GitHub links to this version (and also publish v0.2 of the notebooks on Zenodo), and give versioned links for the online lab as well. compression.lab.climet.eu right now points towards v0.1 of the notebooks and v0.1 of the lab, and we’ll update that then without any of the fully resolved links to previous versions breaking. I added this versioning system precisely so we can change things and correct mistakes without any links breaking.
> 
> What might be useful to add still are some URLs just for the online compression lab, so you could e.g. use compression.lab.climet.eu/v0.1/LICENSE.txt to open specifically this file in the specific version of the lab and notebooks (my plan is to always associate the notebooks with one lab version, though these version numbers don’t need to match).

This sounds good, please feel free to merge when you are happy with it.

**Pull request merged**
