### PR TITLE
Add a vision document

### PR DESCRIPTION
**Pull request by juntyr**
This PR adds the 99-vision.md document, which outlines our larger vision and asks for community contributions to the compression requirements.

### CODE REVIEW

**Review by SF-N — COMMENTED** [review]
Thanks for adding this vision document. It looks good.
I am just wondering about the fields in the google docs table. 
How were they selected?
Aren't some missing? Like e.g. _2 metre temperature_ 
How are the levels set and what does _single level_ mean? E.g. _Specific rain water content_ is a model level field in the IFS.

**Comment by juntyr** [comment]
> I am just wondering about the fields in the google docs table.
> How were they selected?
> Aren't some missing? Like e.g. _2 metre temperature_

I tried to combine the levels from everything in ERA5. Since there were near duplicates, I combined fields (e.g. 2m temperature surface field with multi-level temperature) as the requirements should be at least very similar.

If you can think of extra rows to add, please add them :)

> How are the levels set and what does _single level_ mean? E.g. _Specific rain water content_ is a model level field in the IFS.

Single level usually means surface level (from the ERA5 single level dataset). Should we rename it?

If the field makes sense on more than a single level, you can change it.

**Comment by juntyr** [comment]
Is there anything we should change about this Markdown document or that we should add to the table?

**Comment by SF-N** [comment]
> > I am just wondering about the fields in the google docs table.
> > How were they selected?
> > Aren't some missing? Like e.g. _2 metre temperature_
> 
> I tried to combine the levels from everything in ERA5. Since there were near duplicates, I combined fields (e.g. 2m temperature surface field with multi-level temperature) as the requirements should be at least very similar.
> 
> If you can think of extra rows to add, please add them :)
> 
> > How are the levels set and what does _single level_ mean? E.g. _Specific rain water content_ is a model level field in the IFS.
> 
> Single level usually means surface level (from the ERA5 single level dataset). Should we rename it?
> 
> If the field makes sense on more than a single level, you can change it.

Ok, I will check what is missing and add it.

**Comment by SF-N** [comment]
> Is there anything we should change about this Markdown document or that we should add to the table?

No, I think it looks good. I wouldn't add the table.

**Review by SF-N — APPROVED** [review]
Please merge when you are happy with it.

**Comment by SF-N** [comment]
>  > I am just wondering about the fields in the google docs table.
>  > How were they selected?
>  > Aren't some missing? Like e.g. 2 metre temperature

> 
> I tried to combine the levels from everything in ERA5. Since there were near duplicates, I combined fields (e.g. 2m temperature surface field with multi-level temperature) as the requirements should be at least very similar.
> 
> If you can think of extra rows to add, please add them :)
> 
>  >   How are the levels set and what does single level mean? E.g. Specific rain water content is a model level field in the IFS.
> 
> Single level usually means surface level (from the ERA5 single level dataset). Should we rename it?
> 
> If the field makes sense on more than a single level, you can change it.

I added some more Model level fields and renamed `Single` to `Single/Surface`. Furthermore, I added the label `Pressure+Model` and marked fields that occur on both level types with that.

@juntyr In the vision document, we maybe should explicitly encourage scientists to add new fields to the table.

**Pull request merged**
